baseURL = "https://leandrorosa.github.io/"
languageCode = "en-us"
title = "Leandro Rosa"
theme = "hugo_theme_pickles"
[params]
twitter = "leandroorosa"
github = "leandrorosa"

[languages]
 [languages.en]
    languageName = "English"
    weight= "1"
[languages.pt]
    languageName = "Português"
    weight = 2